[package]
name = "synthesizerlog"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.14.0"
rand = "0.8.0"
basic_waves = "0.1.1"
